name: CEALenv
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - scikit-learn=0.20.1
  - pytorch=1.3.1
  - torchvision=0.4.2
  - imageio
  - opencv
  - scikit-image
  - pandas 
  - seaborn
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - time
  - pillow
  - pip
  - pip:
    - flake8==3.7.9
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - opencv-python